#!/usr/bin/env bash
# Runs the API and the web locally (http://localhost:5123) with the real Google and Tesla clients.
# The secrets are decrypted on the fly (Touch ID) into this process' environment, never written to disk.
set -euo pipefail
cd "$(dirname "$0")/.."
export SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/se-identity.txt}"

while IFS='=' read -r key value; do
  [ -n "$key" ] && export "$(printf '%s' "$key" | tr '[:lower:]' '[:upper:]')=$value"
done < <(sops decrypt --output-type dotenv infrastructure/secrets/production.sops.yaml)

pnpm infra:up
export PUBLIC_BASE_URL=http://localhost:5123
export DATABASE_URL=postgres://charging:charging@localhost:5432/charging
# Seals tokens in the local database only; production uses a key generated by Terraform.
export TOKEN_ENCRYPTION_KEY=ZGV2LW9ubHktdG9rZW4ta2V5LTMyLWJ5dGVzLWxvbmc=
exec pnpm dev
